# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jam1QRBQwujG1nseVtEL2Q8traIg1fT3
"""

#Load the t20 dataset
import pandas as pd

data = pd.read_csv("t20.csv")

#check the columns and values
data.head()

#Drop column Unnamed: 15
droped_colm = data.drop(['Unnamed: 15'], axis=1)
droped_colm.head()

#Drop column Sno
droped_colm = data.drop(['Sno'], axis=1)
droped_colm.head()

#Select all players who have more then 3 hundreds 
selection = data[(data['100'] > 3)]
selection

#Select all players who have highest score more then 50
#data['HS'] = data['HS'].astype(float)
selection = data[data.HS.str.replace('*','0').astype(float) >= 50.0] ['Player']
selection

#How many players who have avg above 35?
data[data.Ave.str.replace('-','0').astype(float) >= 35.0] ['Player'].count()



