# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFEViSqGS6QC7oHri8pgX-RtGyfvq-9I
"""

#Load the file IMDB-Movie-Data.csv in pandas and make title as index column
import pandas as pd

data = pd.read_csv("IMDB-Movie-Data.csv" , index_col="Title")

#Display 5 most repeated values in Director Column
data['Director'].value_counts()

#Filter all movies from Passengers to Gold using value (loc)
prom = data.loc[["Passengers","Gold"]]
prom

#Filter all movies from Passengers to Gold using position (iloc)
prom = data.iloc[[10,21]]
prom

#List all movies from year 2012
condition = data[(data['Year'] == 2012)]
condition

#List all movies having runtime of 120 and above
condition =data[(data['Runtime (Minutes)'] >= 120)]
condition

#List all movies having rating above 6
condition = data[(data['Rating'] > 6)]
condition

#List all movies having metascore above 50
data[data['Metascore'] > 50]

#List all movies having metascore above 60 and ratings above 6 and year 2016
data[
((data['Metascore'] > 50))
& (data['Rating'] > 6) 
& (data['Year'] == 2012)]

#List all movies directed by David Ayer or Adam Mckay and having ratings above 6
data[
    ((data['Director'] == "David Ayer") | (data['Director'] == "Adam Micky"))
& (data['Rating'] > 6)]

#List the movie which has highest rating in 2016 (Hint: solve in two steps, first filter the data of 2016
#and save in another variable and then filter the highest rating from that)
condition = data[(data['Year'] == 2016)]
condition = condition['Rating']
condition.max()

#List the movie which has highest metascore in 2016 (Hint: solve in two steps, first filter the data of
#2016 and save in another variable and then filter the highest metascore from that)
condition = data[(data['Year'] == 2016)]
condition = condition['Metascore']
condition.max()

#List the movie which has highest revenue in 2016 (Hint: solve in two steps, first filter the data of
#2016 and save in another variable and then filter the highest revenue from that)
condition = data[(data['Year'] == 2016)]
condition = condition['Revenue (Millions)']
condition.max()

